name: Build & Push
on:
  pull_request:
    branches:
        - main
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: false
      - name: "Build WASM module"
        run: |
          cd ./wasm && GOOS=js GOARCH=wasm go build -o ../crowdsec-playground/public/main.wasm
      - name: "Build react app"
        run: |
          cd ./crowdsec-playground && npm ci && npm run build
      - name: "Push to gh-pages"
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./crowdsec-playground/build
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}